### ISSUE TITLE
Add maintainers.md

### ISSUE THREAD

**Issue by MALPI** [failsafe-lib/failsafe#112]
By adding a `maintainers.md` one could check whom to contact in case of questions or bug reports?

**Comment by jhalterman** [comment]
I'd like to get Failsafe over to a github organization (unfortunately github.com/failsafe is occupied, but currently unused), then it would be good to add something like `maintainers.md`.

**Comment by jhalterman** [comment]
Digging through old issues - we still aren't at an organization (I haven't been able to get github.com/failsafe - the owner is not responsive). Any thoughts on github.com/failsafelib ?

**Comment by MALPI** [comment]
Sounds good to me. Take it while it's available @jhalterman

**Comment by jhalterman** [comment]
If maintainers.md is mostly about contacting for bug reports or questions, I'd rather people use github issues or gitter, so that questions/bugs are publicly visible to everyone. If there's another good reason for maintainers, feel free to reopen, else closing for now.
