### ISSUE TITLE
Consider adding next attempt time in ExecutionAttemptedEvent

### ISSUE THREAD

**Issue by jhalterman** [failsafe-lib/failsafe#232]
When handling an ExecutionAttemptedEvent such as via onFailedAttempt, it would be nice to be able to log when the next execution may take place.

**Comment by szpak** [comment]
I've just wanted to report the same idea. When you have constant delay, it might be available in the enclosing class to use during the `onFailedAttempt` listener creation. However, it's not always possible, especially using jitter.

**Comment by jhalterman** [comment]
Indeed - I think this would only work for fixed or backoff delays. Computed and random delays it would not work, and jitter would not be included either.

**Comment by jansohn** [comment]
+1 for this. I'd also expect this to only work for fixed and backoff delays.

**Comment by jhalterman** [comment]
@jansohn I should mention, instead of using the onFailedAttempt event handler, you can use the onRetryScheduled event handler, which does mention when the next retry will be performed:

https://failsafe.dev/javadoc/dev/failsafe/RetryPolicyBuilder.html#onRetryScheduled-dev.failsafe.event.EventListener-

This event is delivered after Failsafe has decided that a failure occurred, that another retry is needed, and when it should be performed, some of which isn't known yet when the onFailedAttempt event fires a bit earlier.

**Comment by jansohn** [comment]
> @jansohn I should mention, instead of using the onFailedAttempt event handler, you can use the onRetryScheduled event handler, which does mention when the next retry will be performed (Failsafe 3 javadoc):
> 
> https://failsafe.dev/javadoc/dev/failsafe/RetryPolicyBuilder.html#onRetryScheduled-dev.failsafe.event.EventListener-
> 
> This event is delivered after Failsafe has decided that a failure occurred, that another retry is needed, and when it should be performed, some of which isn't known yet when the onFailedAttempt event fires a bit earlier.
> 
> I think this event, which didn't exist when I opened the issue, is a good enough solution to consider this issue closed. Feel free to reopen if you feel otherwise.

thanks, that worked like a charm!
