### ISSUE TITLE
Split retry by MaxDuration and MaxAttempts

### ISSUE THREAD

**Issue by Donald522** [failsafe-lib/failsafe#241]
I faced a situation when I need to retry operation during specified time interval and fail operation after this interval.

I am creating policy in such way:

```
RetryPolicy<Object> retry = new RetryPolicy<>()
                .withDelay(Duration.ofSeconds(1))
                .withMaxDuration(Duration.ofMinutes(1))
                .onFailedAttempt(e -> System.out.println("Attempt failed"));
```

So I expect 60 attempts before operation is failed. Instead, in logs I see:

```
Attempt failed
Attempt failed
Attempt failed
Exception in thread "main" Sample1Fs$MeException: FAILED: OOPS!
```

After debugging, I figured out, that default max attempts is set to 2 and affect my retry policy.

After adding line "withMaxAttempts(-1)" to policy configuration, it started to work as expected.

```
RetryPolicy<Object> retry = new RetryPolicy<>()
                .withDelay(Duration.ofSeconds(1))
                .withMaxDuration(Duration.ofMinutes(1))
                .withMaxAttempts(-1)
                .onFailedAttempt(e -> System.out.println("Attempt failed"));
```

This line looks redundant and decrease readability in such case.

Does it make sense to set maxRetries field in RetryPolicy.java to "-1" in maxDuration() method?

**Comment by jhalterman** [comment]
> Does it make sense to set maxRetries field in RetryPolicy.java to "-1" in maxDuration() method?

As you noticed, 3 attempts is the default, and this [is](https://jodah.net/failsafe/retry/#attempts) [documented](https://jodah.net/failsafe/javadoc/net/jodah/failsafe/RetryPolicy.html#RetryPolicy--) FWIW. Not having a default number of max attempts would mean other users would be surprised when retries happen forever. 

So what you're doing is the correct approach and is not redundant since you're expressing that you want something other than the default.

**Comment by Donald522** [comment]
I am not spealing about removing default number of max attempts.

I speak about that basically I have a choice for retry policy: I can limit it euther by time or by number of attempts.
So, for me it sounds reasonable when I set maxDuration then I do not need to set number of max attempts to -1 manually. 
For example, when I need to limit retry policy by max attempts I only need to set maxAttempts parameter and there is no need to set maxDuration to -1 or smth else.
Hope my point is clear :)

**Comment by jhalterman** [comment]
Yes I understand. I'd have to consider whether setting maxDuration should remove the default maxAttempts...

**Comment by Tembrel** [comment]
> Yes I understand. I'd have to consider whether setting maxDuration should remove the default maxAttempts...

That could break existing uses, if someone was relying on the documented behavior of 3 attempts as the default max, but also using a (very large) max duration.

Documenting the max attempts default as a note in `withMaxDuration` wouldn't break code but would inform people who don't want to limit the number of attempts to use `withMaxAttempts(-1)`.

**Comment by jhalterman** [comment]
I don't think that removing maxAttempts if maxDuration is set would be a good idea for the reasons discussed above. A note was also previously added to the `withMaxDuration` docs about the behavior.
