### ISSUE TITLE
CircuitBreaker reports 0 successes transitioning into a closed state

### ISSUE THREAD

**Issue by timothybasanov** [failsafe-lib/failsafe#247]
When a circuit breaker transitions into a closed state due to
`setFailureThreshold(breaker.getFailureThreshold() != null ? breaker.getFailureThreshold() : ONE_OF_ONE);`
call in `net.jodah.failsafe.internal.ClosedState.java:31` it always has 0 successes by the time listener is called.

```java
import net.jodah.failsafe.CircuitBreaker;
import net.jodah.failsafe.Failsafe;
import net.jodah.failsafe.FailsafeExecutor;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.JUnitCore;

import java.time.Duration;
import java.util.concurrent.atomic.AtomicReference;

public class TestCircuitBreaker {
    public static void main(String[] args) {
        JUnitCore.main("TestCircuitBreaker");
    }

    @Test
    public void testSuccessCountCircuitOpen() throws Exception {
        AtomicReference<CircuitBreaker<?>> circuitBreaker = new AtomicReference<>();
        circuitBreaker.set(new CircuitBreaker<>()
                                   .withDelay(Duration.ZERO)
                                   .withFailureThreshold(1)
                                   .withSuccessThreshold(2, 4)
                                   .onClose(() -> Assert.assertEquals("Expected 2/4 successes", 2,
                                                                      circuitBreaker.get().getSuccessCount())));
        final FailsafeExecutor<?> failsafeExecutor = Failsafe.with(circuitBreaker.get());
        try {
            failsafeExecutor.run(ctx -> {
                throw new RuntimeException("Trip CB open");
            });
            Assert.fail();
        } catch (RuntimeException ignored) {
        }
        for(int i=0; i<4; i++) {
            failsafeExecutor.run(ctx -> {});
        }
        Assert.assertEquals(circuitBreaker.get().getState(), CircuitBreaker.State.CLOSED);
    }
}
```

**Comment by jhalterman** [comment]
@timothybasanov Thanks - looking at this. Our of curiosity, I noticed you use a reference to the CircuitBreaker inside the `onClose` method. Is that something you do in production code or was it just for this test?

**Comment by jhalterman** [comment]
The reason the successCount is 0 is because execution stats reflect executions in the current state. Immediately after transitioning to CLOSED (such as in `onClosed`), there will have been 0 executions so far in that state. So this is expected. The [Javadocs](https://jodah.net/failsafe/javadoc/net/jodah/failsafe/CircuitBreaker.html#getSuccessCount--) mention this a bit.

That said, if you don't think this is desirable behavior or have use cases for something different, I'd love to hear about it.

**Comment by timothybasanov** [comment]
Yep, I've discovered it in the live code.
Custom subclass of CB has a method that is attached as a listener to all state changes via a method reference. It's used to log all state changes and includes failures/successes/threshold for a specific CB at a time of a change. It's important that I read then at runtime as all these values are mutable in my code.

**Comment by jhalterman** [comment]
Closing for now unless there's a suggestion for how the current behavior should be changed/improved.
