### ISSUE TITLE
preexecute + standalone circuit breaker

### ISSUE THREAD

**Issue by gokelly** [failsafe-lib/failsafe#249]
Hi,
What purpose does preexecute serve? Testing circuit breaker in standalone mode the circuit seems to be opened and closed when expected without making any calls to preexecute (or recordSuccess).

**Comment by jhalterman** [comment]
When in a half-open state we don't want to allow too many concurrent executions. So we limit the circuit breaker to only allow as many executions as are configured in the success or failure threshold. Calling `preExecute` helps the CircuitBreaker track how many executions are in progress.

**Comment by jhalterman** [comment]
Closing for now. Please reopen if needed for further discussion.
