### ISSUE TITLE
Consider more explicit functional composition APIs

### ISSUE THREAD

**Issue by jhalterman** [failsafe-lib/failsafe#254]
For some ideas, see:

- https://github.com/jhalterman/failsafe/issues/253#issuecomment-642194567
- https://github.com/jhalterman/failsafe/issues/253#issuecomment-642234984
- https://github.com/jhalterman/failsafe/issues/253#issuecomment-642253602

**Comment by Tembrel** [comment]
I don't think you'd want to add composability to policies unless you __also__ have a solid guarantee of [immutability for policies](#47), otherwise `p3 = p1.andThen(p2)` followed by, say, `p1.mutativeMethod()` might yield surprising results for `p3`.

The same danger exists for `Failsafe.with(p2, p1)` or `Failsafe.of(p1).andThen(p2)`, of course, but I guess my expectations are different when it isn't the policies themselves doing the composing.

**Comment by jhalterman** [comment]
Another more verbose but clear possibility:

```java
PolicyComposition composition = fallback.wrap(retryPolicy.wrap(circuitBreaker.wrap(timeout)));
Failsafe.with(composition).get(this::connect);
```

This mirrors the flattened out version nicely:

```java
Failsafe.with(fallback, retryPolicy, circuitBreaker, timeout).get(this::connect);
```

**Comment by Tembrel** [comment]
Hard to imagine anyone writing out the nested version; it's hard to read, let alone write.

I've forgotten what you (@jhalterman) didn't like about:
```java
result = Failsafe.with(timeout)
    .within(circuitBreaker)
    .within(retryPolicy)
    .within(fallback)
    .get(this::connect);
```
Or:
```java
result = Failsafe.with(fallback)
    .around(retryPolicy)
    .around(circuitBreaker)
    .around(timeout)
    .get(this::connect);
```
Or both!
```java
result = Failsafe.with(retryPolicy)
    .around(circuitBreaker)
    .around(timeout)
    .within(fallback)
    .get(this::connect);
```
(That's unambiguous but hard to understand. I imagine people would stick to uniform `within` or `arround`, but it would be nice to have the option.)

A minor perq of the fluent form is that you can temporarily comment out a policy like so:
```java
result = Failsafe.with(fallback)
    .around(retryPolicy)
    //.around(circuitBreaker)
    .around(timeout)
    .get(this::connect);
```

**Comment by jhalterman** [comment]
> I've forgotten what you (@jhalterman) didn't like about:

Partly naming (I like @whiskeysierra's suggestion of borrowing `Function`'s `compose` naming), but also some tradeoffs depending on the API approach. Also as pointed out by @whiskeysierra above, we have 2 general options for the composition API:

1. Define compositions via the policies:

```java
Failsafe.with(fallback.compose(retryPolicy)
    .compose(circuitBreaker)
    .compose(timeout))
  .get(this::connect);
```

2. Define compositions via the `Failsafe`/`FailsafeExecutor` API:

```java
Failsafe.with(fallback)
  .compose(retryPolicy)
  .compose(circuitbreaker)
  .compose(timeout)
  .get(this::connect);
```

I'd slightly lean towards option 2. Each `.compose` should probably return a new `FailsafeExecutor` so that an existing executor doesn't accidentally get mutated unexpectedly. The only downside of this option that I can think of right now is the composition could possibly be mixed with other configuration, ex:

```java
Failsafe.with(fallback)
  .compose(retryPolicy)
  .with(executorService)
  .compose(circuitBreaker)
  .onComplete(e -> ....)
  .compose(timeout)
  .get(this::connect);
```

...but maybe not a big deal. Any thoughts or preferences?

**Comment by jhalterman** [comment]
Pushed a PR for this. Feel free to weigh in there: #285.

**Comment by jhalterman** [comment]
3.0 has been released, which includes this improvement. The policy docs page also describes how composition works with a sequence diagram:

https://failsafe.dev/policies/#policy-composition
