### ISSUE TITLE
Support RetryPolicy.onRetryScheduled

### ISSUE THREAD

**Issue by jhalterman** [failsafe-lib/failsafe#278]
This would clarify when a retry is pending vs when it's actually happening, since there is a delay between these two events. The onRetryScheduled event could indicate how long until the retry is due to occur.

**Comment by Tembrel** [comment]
Should be possible to guarantee that the `retryScheduled` and `retry` events will be received in that order, right? Would `retryScheduled` __always__ be triggered, or only when the delay is nonzero?

**Comment by jhalterman** [comment]
Yes, that ordering would be ensured. It's a good question about the delay. What do you think? For users of this event, it might be simpler if it always fires, even if the scheduled delay is zero.

The reason I started thinking about this is I'm working to improve how Timeouts work with retries. A Timeout composed outside of a retry should cancel any retries. In that case, a retry might get scheduled but never actually occur if the Timeout fires in the meantime.

**Comment by Tembrel** [comment]
Less surprising if `onRetryScheduled` always fires. User can query the scheduled delay, I assume, so if they want to distinguish the zero delay case, they can.

**Comment by jhalterman** [comment]
Closed by 798929715e2428ee0162121c3dc1df92265ed19a

**Comment by jhalterman** [comment]
This is fixed in 2.4.2.
