### ISSUE TITLE
java.util.ConcurrentModificationException in FailurePolicy.isFailure()

### ISSUE THREAD

**Issue by erdaldogan** [failsafe-lib/failsafe#282]
When using the policy below with the FailSafe 2.4.1 I get ConcurrentModificationException error. 
```
Exception in thread "Thread-1444" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at net.jodah.failsafe.FailurePolicy.isFailure(FailurePolicy.java:155)
	at net.jodah.failsafe.FailurePolicy.isFailure(FailurePolicy.java:141)
	at net.jodah.failsafe.PolicyExecutor.isFailure(PolicyExecutor.java:118)
	at net.jodah.failsafe.PolicyExecutor.postExecute(PolicyExecutor.java:67)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:210)
	at metrics.functions.newrelic.NewRelicEventSender.run(NewRelicEventSender.java:67)
	at java.lang.Thread.run(Thread.java:748)
```

Retry Policy is as follows
```
RETRY_POLICY.handle(IOException.class)
                .withMaxRetries(10)
                .withDelay(Duration.ofSeconds(2))
                .onFailedAttempt(e -> logger.error("Send metrics attempt failed", e.getLastFailure()))
                .onRetry(e -> logger.warn("Failure #{}. Retrying.", e.getAttemptCount()))
                .onRetriesExceeded(e -> logger.warn("Failed to connect. Max retries exceeded."));
```

At some point I dynamically update the contents of the list using the iterators, by using `iterator.remove()` method, hence, I don't expect this part to be problem. 

```
Iterator<ApplicationMetric> iterator1 = applicationMetricList.stream()
                .filter(applicationMetric -> !ignoredEventTypes.contains(applicationMetric.getEventType()))
                .iterator();
        while (iterator1.hasNext()) {
            ApplicationMetric applicationMetric = iterator1.next();

            Iterator<Map.Entry<String, Object>> iterator = applicationMetric.getDetails().entrySet().iterator();
            while (iterator.hasNext()) {
                Map.Entry<String, Object> entry = iterator.next();
                Object value = entry.getValue();

                if (EXACT_SET.contains(entry.getKey().toLowerCase())) {
                    iterator.remove();
                    continue;
                }

                if (value instanceof Number || value instanceof Boolean || value == null) {
                    continue;
                } else if (value instanceof String) {
                    entry.setValue(checkStringAndTrimIfNecessary(String.valueOf(value)));
                } else {
                    try {
                        entry.setValue(checkStringAndTrimIfNecessary(JSON.toJson(value)));
                    } catch (IOException e) {
                        logger.error("Cannot convert non-basic field to JSON: " + e.getMessage());
                    }
                }
            }
        }
```

**Comment by Tembrel** [comment]
> When using the policy below with the FailSafe 2.4.1 I get ConcurrentModificationException error.

Is this new behavior with the 2.4.1 release? If not, then I suspect the exception is not due to anything within Failsafe.


> At some point I dynamically update the contents of the list ...

*At some point*: can you give us more detail? In particular, is the code fragment above involving `iterator1` part of the task being executed with Failsafe? Or is it performed outside of the Failsafe execution? (What is happening in the Failsafe task, in that case?)

The stack trace shows `ConcurrentModificationException` thrown within `ArrayList$Itr.next`, because `checkForComodification` determined that the list this iterator is iterating has been modified by some action other than a call to `remove()` on that iterator. That could be because of `remove()` was called on a __different__ iterator; simply using `it.remove()` doesn't prevent `ConcurrentModificationException` being thrown from __other__ iterations or actions.

I think the use of `remove` is a red herring, anyway, because the `entrySet()` iteration would be using [an `AbstractSet`](https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/HashMap.java#l1001) under the covers rather than an `ArrayList`.

The most likely explanation is that another thread is modifying `applicationMetricList` during the `while (iterator1.hasNext())` loop, but there's not enough information for me to be sure.

**Comment by erdaldogan** [comment]
> Is this new behavior with the 2.4.1 release?
I have not used any previous versions of the FailSafe. Hence, I am not able to answer this. I will try to duplicate it with 2.4.0 and report the results.

> At some point: can you give us more detail?
Code fragment I shared above _was_ the part of the task being executed with FailSafe. I use failsafe for sending some data to New Relic platform. Before sending it, I process it a little. Fragment I shared in previous message used belongs to data processing section. I removed the iterator.remove part and got the same exception again.

Basing on the stack trace, since there were not any other classes and function, I thought it might have been sourced from the FailSafe.

> The most likely explanation is that another thread is modifying applicationMetricList during the while (iterator1.hasNext()) loop, but there's not enough information for me to be sure.

```applicationMetricList``` is not a shared variable, locally initialized in threads. Therefore I am not sure if this is the case. I will try to dig more on the problem and keep this issue updated.

**Comment by Tembrel** [comment]
Another thing to try is removing the use of iterators entirely:
```java
applicationMetricList.stream()
    .filter(applicationMetric -> !ignoredEventTypes.contains(applicationMetric.getEventType()))
    .map(ApplicationMetric::getDetails)
    .forEach(details -> {

    details.entrySet().removeIf(entry ->
        EXACT_SET.contains(entry.getKey().toLowerCase()));

    for (Map.Entry<String, Object> entry : details.entrySet()) {
        Object value = entry.getValue();
        if (value == null || value instanceof Number || value instanceof Boolean) {
            // leave alone
        } else if (value instanceof String) {
            entry.setValue(checkStringAndTrimIfNecessary(String.valueOf(value)));
        } else {
            try {
                entry.setValue(checkStringAndTrimIfNecessary(JSON.toJson(value)));
            } catch (IOException e) {
                logger.error("Cannot convert non-basic field to JSON: " + e.getMessage());
            }
        }
    }
});
```
If this either works or yields a different stack trace, it might give you useful information.

**Comment by erdaldogan** [comment]
Above fragment is not parallelized anymore and the issue seems to be vanished. Evidently, the problem was not related with the FailSafe. Sorry for the disruption, and thank you for your sincere approach to the problem.
