### ISSUE TITLE
Please add `withMaxDelay(Duration)` and `withBackoff(Duration, Duration)` to `RetryPolicy`

### ISSUE THREAD

**Issue by JayBazuzi** [failsafe-lib/failsafe#293]
`RetryPolicy.withBackoff()` currently takes two `long` and a shared unit, which makes it awkward when the two values are far apart from each other:

```
new RetryPolicy<>()
    .withDuration(1, 300000 /* 5 minutes, I think */), ChronoUnit.MILLIS));
```

I wish I could write:

```
new RetryPolicy<>()
    .withDelay(Duration.ofMillis(1)
    .withMaxDelay(Duration.ofMinutes(5));
```

or 

```
new RetryPolicy<>()
    .withBackoff(Duration.ofMillis(1), Duration.ofMinutes(5));
```

**Comment by jhalterman** [comment]
Thanks for the suggestion. The main reason for this is that Duration was added in Java 9 whereas Failsafe is still based on Java 8 in order to try and support more users, some Android users, etc. I'll keep this issue open for when we upgrade the Java version we support.

**Comment by jhalterman** [comment]
Good suggestion. `withBackoff(Duration, Duration)` seems worth supporting.

**Comment by jhalterman** [comment]
3.0 has been released, which includes this improvement.
