### ISSUE TITLE
Typo: Execution Cancellation: Extra )

### ISSUE THREAD

**Issue by numeralnathan** [failsafe-lib/failsafe#333]
Please correct the typo on this https://failsafe.dev/execution-cancellation/ for this line.

`scheduler.schedule(()` -> call.cancel(false), 10, TimeUnit.SECONDS);`

There is an extra `)` after `false`.  Perhaps, the code is correct and I struggled with Lisp.

**Comment by Tembrel** [comment]
Looks ok to me:
```java
scheduler.schedule(() -> call.cancel(false), 10, TimeUnit.SECONDS);
```
`schedule` takes 3 arguments, `callable`, `delay`, and unit. 

`cancel` takes one boolean argument.

Reformatting makes this more obvious:

```java
scheduler.schedule(
    () -> call.cancel(false)
    10,
    TimeUnit.SECONDS
);
```

**Comment by numeralnathan** [comment]
Thank you.  That `)` tripped me up.
