### ISSUE TITLE
Why does CheckedPredicate exist?

### ISSUE THREAD

**Issue by spartanhooah** [failsafe-lib/failsafe#363]
Is there any reason that `CheckedPredicate` cannot be replaced with `java.util.function.Predicate`? The former seems like a simplified version of the latter.

**Comment by Tembrel** [comment]
The signature of the `CheckedPredicate::test` method is
```java
boolean test(T t) throws Throwable;
```
and for plain `Predicate::test`, it is just
```java
boolean test(T t);
```
They are both functional interfaces, though. You can use a lambda or method reference that conforms to `java.util.function.Predicate` in contexts that accept a `CheckedPredicate`, but the latter allows you to write handlers that throw checked exceptions, e.g.,
```java
RetryPolicy retryPolicy = RetryPolicy.builder()
    .handleResultIf(result -> needsRetry(result))
    .build();
```
where `needsRetry` can throw a checked exception. (If it does, the policy will __not__ handle the result.)

**Comment by spartanhooah** [comment]
I see. Thank you for the explanation.
