### ISSUE TITLE
Guidance around CheckedPredicate

### ISSUE THREAD

**Issue by ysaadi** [failsafe-lib/failsafe#367]
In the 2.x version of this repo, we were defining a predicate in a way similar to so:
`Pridicate<ApiResponse<?> predicate = (response -> response.getStatusCode().isSuccessful())`

With the switch to checkedResponse, this code no longer works as ApiResponse is expected to extend throwable.  Any idea of what I am doing wrong/how I should approach this differently?

**Comment by Tembrel** [comment]
Can you give more context? What is the code that no longer works in Failsafe 3.x? The snippet you provided doesn't tell us enough.

**Comment by jhalterman** [comment]
Closing as stale.
