### ISSUE TITLE
RetryPolicy handleIf not working with DynamoDbException in predicate

### ISSUE THREAD

**Issue by ntthaibk** [failsafe-lib/failsafe#370]
When I'm doing failsafe with this handleIf statement in the RetryPolicy builder

```java
RetryPolicy.builder()
                .withBackoff(5, maxDelay, ChronoUnit.SECONDS)
                .withMaxRetries(maxRetry)
                .handle(DynamoDbException.class)
                .handleIf(e -> {
                    if (e instanceof IllegalStateException) {
                        return e.getMessage().contains("Record not Found");
                    }
                    if (e instanceof DynamoDbException) {
                        return e.getMessage().contains("Rate exceeded");
                    }
                    return false;
                })
                .onSuccess(e -> log.info("DynamoDb query success"))
                .onFailedAttempt(e -> log.error("No record found with exception {}, attempted: {}", e.getLastException(), e.getAttemptCount()))
                .build();
    }
```

With other kind of Exception, e.g. IllegalStateException, RuntimeException with custom message, it can match with predicate and handle correctly. But for that DynamoDbException, regardless of the message, it always retry.

I don't know if we can do something to enhance so the predicate can catch the condition  e.getMessage().contains("Rate exceeded"); correctly

Thank you guys

**Comment by Tembrel** [comment]
What happens when you remove the `handle(...)` line:
```java
    //.handle(DynamoDbException.class)
```
I'm guessing you're following the model on [this page](https://failsafe.dev/policies/#failure-handling):
![image](https://github.com/failsafe-lib/failsafe/assets/237258/9477c21b-2b30-43ac-a7ab-13dda7138dee)

I think that sample code is demonstrating different possibilities rather than being a single model of how to do it.

**Comment by jhalterman** [comment]
> I think that sample code is demonstrating different possibilities rather than being a single model of how to do it.

That's correct.

**Comment by Tembrel** [comment]
I wonder if there's a simple markdown way to make that clear.

**Comment by ntthaibk** [comment]
thanks guys, it worked perfectly now.
