### ISSUE TITLE
CircuitBreakerBuilder withSuccessThreshold documentation whoopsy

### ISSUE THREAD

**Issue by GalBachar** [failsafe-lib/failsafe#384]
https://github.com/failsafe-lib/failsafe/blob/ceb14ace0c665a7a7fef1d0440c14d7122423343/core/src/main/java/dev/failsafe/CircuitBreakerBuilder.java#L274

Should say:
The number of consecutive successful executions that must occur in order to **close** the circuit

**Comment by jhalterman** [comment]
Thanks for pointing this out.
