### ISSUE TITLE
Consider time based thresholds for CircuitBreaker

### ISSUE THREAD

**Issue by jhalterman** [failsafe-lib/failsafe#45]
For example, where .5 executions fail over 1 minute period. See Polly's advanced circuit breaker as a reference:

https://github.com/App-vNext/Polly

Either requires windowing or inexact stats, neither of which are ideal.

**Comment by whiskeysierra** [comment]
Interesting idea, but I'd wait for more :+1:.

**Comment by jhalterman** [comment]
This was added to Failsafe.
