### ISSUE TITLE
Consider better support for bulkheads and rate limiting

### ISSUE THREAD

**Issue by jhalterman** [failsafe-lib/failsafe#78]
Consider better support for bulkheads, perhaps through named management, and rate limiting via semaphores (user provided?)

**Comment by whiskeysierra** [comment]
What is your understanding of bulkheads in the context of failsafe? Would you consider rate limiting to be within failsafe's scope at all?

**Comment by jhalterman** [comment]
Rate limiter could have a rampdown from the time it's created, where for the first 5 minutes the rate of allowed concurrency graduallt increases to allow more requests. This would allow services to gradually process reconnects and resource creation after a disconnect/reconnect event.

**Comment by jhalterman** [comment]
Closing in favor of specific issues for each policy.
