### ISSUE TITLE
Create a FailsafeExecutor with no policies

### ISSUE THREAD

**Issue by neilgsyoung** [failsafe-lib/failsafe#95]
In order to provide some additional Fault Tolerant functionality that works with Failsafe, we need to work with an instance of Failsafe. In our situation we *may* be setting up a Fault Tolerant execution that has neither a CircuitBreaker nor a RetryPolicy. We could get this instance by calling Failsafe.with() providing a "no-op" RetryPolicy. 

One quick way to implement this in Failsafe would be to change the visibility of RetryPolicy.NEVER to public. In our situation this allows us to work with an execution that has no RetryPolicy or, if required, to subsequently apply a real instance of RetryPolicy to the execution.

**Comment by jhalterman** [comment]
Hi @neilgsyoung 

First, since I'm curious, is any of the additional fault tolerant stuff you're adding around Failsafe stuff that we should consider adding to Failsafe?

Are you opposed to calling:

```
Failsafe.with(new RetryPolicy().withMaxRetries(0))
```

For your no-op SyncFailsafe instance?

**Comment by neilgsyoung** [comment]
Hi @jhalterman 

We will keep a close eye on whether it would be best to add additional function to Failsafe.

If there's a better way to get a no-op Failsafe instance I'd be happy to go with it. I don't think we can use the call you suggest because we'll get a new RetryPolicy instance which means we'll fail the test in FailsafeConfig.with(RetryPolicy),

Assert.state(this.retryPolicy == RetryPolicy.NEVER, "A retry policy has already been configurd");

**Comment by jhalterman** [comment]
Not sure if this is still relevant, but it could be possible now with `FailsafeExecutor` to create a `FailsafeExecutor` with no policies configured (though at present, that default constructor is not exposed). I'm interested to hear more about the use case where this is helpful.

**Comment by jhalterman** [comment]
`Failsafe.none()` was added in 2.4.2.
